"""
exporter.py
===========
Generates a well-formatted Markdown report from a list of MaterialData objects.

Version: 2.0
"""

from datetime import datetime
from scraper import MaterialData


def _row(label: str, value: str) -> str:
    """One key-value bullet line (skipped if value is empty)."""
    return f"- **{label}:** {value}\n" if value else ""


def _list_items(label: str, items: list) -> str:
    """Render a list under a label."""
    if not items:
        return ""
    lines = f"- **{label}:**\n"
    for item in items:
        lines += f"  - {item}\n"
    return lines


def _material_section(mat: MaterialData) -> str:
    """Convert one MaterialData to a Markdown section."""

    if not mat.found:
        return f"\n## {mat.name}\n\n> ⚠️ **Not Found:** {mat.error}\n\n---\n"

    md = f"\n## {mat.name}\n"
    if mat.page_url:
        md += f"\n🔗 [View on PubChem]({mat.page_url})\n"

    # Identifiers
    block = (
        _row("CAS Number", mat.cas_number)
        + _row("FEMA Number", mat.fema_number)
        + _row("IUPAC Name", mat.iupac_name)
        + _list_items("Synonyms", mat.synonyms)
    )
    if block.strip():
        md += "\n### Identifiers\n" + block

    # Molecular
    block = (
        _row("SMILES", f"`{mat.smiles}`" if mat.smiles else "")
        + _row("Molecular Formula", mat.molecular_formula)
        + _row("Molecular Weight", mat.molecular_weight)
    )
    if mat.structure_image_url:
        block += f"- **Structure:** ![structure]({mat.structure_image_url})\n"
    if block.strip():
        md += "\n### Molecular Information\n" + block

    # Odor
    block = (
        _row("Odor Description", mat.odor_description)
        + _row("Odor Type", mat.odor_type)
        + _row("Odor Strength", mat.odor_strength)
    )
    if block.strip():
        md += "\n### Odor Profile\n" + block

    # Note
    if mat.note_classification:
        md += "\n### Note Classification\n"
        md += f"- **Perfume Note:** {mat.note_classification}\n"

    # Performance
    block = _row("Tenacity", mat.tenacity) + _row("Duration", mat.tenacity_hours)
    if block.strip():
        md += "\n### Performance\n" + block

    # Physical
    block = (
        _row("Appearance", mat.appearance)
        + _row("Boiling Point", mat.boiling_point)
        + _row("Flash Point", mat.flash_point)
        + _row("Vapor Pressure", mat.vapor_pressure)
        + _row("Solubility", mat.solubility)
        + _row("Density", mat.density)
        + _row("Refractive Index", mat.refractive_index)
        + _row("LogP", mat.logp)
    )
    if block.strip():
        md += "\n### Physical & Chemical Properties\n" + block

    # Safety
    block = _row("IFRA Guidelines", mat.ifra_guidelines) + _row("Usage Levels", mat.usage_levels)
    if block.strip():
        md += "\n### Safety & Formulation\n" + block

    # Blending
    if mat.blends_well_with:
        md += "\n### Blending Suggestions\n"
        md += _list_items("Blends Well With", mat.blends_well_with)

    md += "\n---\n"
    return md


def generate_full_report(materials: list) -> str:
    """Compile a complete Markdown report for all materials."""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    header = (
        "# 🧪 Perfume Raw Materials Analysis Report\n\n"
        f"**Generated:** {ts}  \n"
        f"**Materials analyzed:** {len(materials)}  \n"
        f"**Data source:** [PubChem](https://pubchem.ncbi.nlm.nih.gov/) + built-in perfumery DB  \n"
        "\n---\n"
    )
    toc = "\n## Table of Contents\n\n"
    for i, m in enumerate(materials, 1):
        icon = "✅" if m.found else "❌"
        toc += f"{i}. {icon} {m.name}\n"
    toc += "\n---\n"

    body = ""
    for m in materials:
        body += _material_section(m)

    footer = (
        "\n---\n*Report generated by Perfume Raw Materials Analyzer v2.0  \n"
        "Molecular data: PubChem (NIH) · Perfumery data: built-in knowledge base*\n"
    )
    return header + toc + body + footer
