#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────
// tools/codemap.mjs — generate .codemap.md from section banners
//
// Why
//   The repo's source files (index.html, formulation.html,
//   formulation_engine.js) are large monolithic SPAs. Each one
//   holds its CSS, HTML, and JS together so a single grep can
//   surface a lot of irrelevant text. This tool walks every
//   tracked file and harvests the section banners + top-level
//   function declarations into a single markdown index, so a
//   future contributor (human or LLM) lands on the right line
//   range with one Read call.
//
// Usage
//   node tools/codemap.mjs               # writes .codemap.md
//   node tools/codemap.mjs --check       # exits non-zero if stale
//
// Conventions detected
//   • Banner comments matching one of these patterns kick off a
//     new section header in the output:
//       /* ===== Title ===== */          (CSS / JS block-comment)
//       // ===== Title =====              (JS line-comment)
//       // ── Title ──                    (JS line-comment, em-dash)
//       // MODULE: Title                  (JS line-comment)
//   • For .js / inline <script> blocks we additionally surface
//     `function name(`, `async function name(`, and module-scope
//     `const/let X =` declarations.
//
// Output
//   .codemap.md at the repo root. Stable enough to diff in
//   pull requests — line numbers shift, names don't.
// ─────────────────────────────────────────────────────────────

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(new URL('..', import.meta.url).pathname);
const TARGETS = [
  { path: 'index.html',           label: 'Analyzer page'           },
  { path: 'formulation.html',     label: 'Formulator page'         },
  { path: 'formulation_engine.js',label: 'Formulator engine module'},
  { path: 'formulation_data.js',  label: 'Formulator data module'  },
  { path: 'taxonomy.js',          label: 'Shared Edwards-2021 taxonomy'},
  { path: 'lib/utils.mjs',        label: 'Shared utilities'        },
  { path: 'sw.js',                label: 'Service worker'          },
  { path: 'tools/lint-blends.mjs',label: 'Blends linter (CLI tool)'},
];

const BANNER_PATTERNS = [
  // /* ===== Title ===== */
  /^\s*\/\*\s*={3,}\s*([^=].*?)\s*={3,}\s*\*\/\s*$/,
  // // ===== Title =====
  /^\s*\/\/\s*={3,}\s*([^=].*?)\s*(?:={3,})?\s*$/,
  // // ── Title ── (em-dash variant the repo already uses)
  /^\s*\/\/\s*[─━]{2,}\s*([^─━].*?)\s*[─━]{2,}\s*$/,
  // // MODULE: Title
  /^\s*\/\/\s*MODULE:\s*(.+?)\s*$/,
];

const FUNC_RE   = /^\s*(?:async\s+)?function\s+(_?[A-Za-z][\w$]*)\s*\(/;
const CONST_RE  = /^\s*(?:const|let)\s+([A-Z][\w$]*)\s*=/;
const MIN_LINES_BETWEEN_HEADINGS = 3;

function classify(line) {
  for (const re of BANNER_PATTERNS) {
    const m = line.match(re);
    if (m) return { kind: 'section', title: m[1].trim() };
  }
  const fm = line.match(FUNC_RE);
  if (fm) return { kind: 'fn', title: fm[1] };
  const cm = line.match(CONST_RE);
  if (cm) return { kind: 'const', title: cm[1] };
  return null;
}

function scanFile(absPath) {
  const text = fs.readFileSync(absPath, 'utf8');
  const lines = text.split('\n');
  const sections = [];
  let lastHeadingLine = -Infinity;
  for (let i = 0; i < lines.length; i++) {
    const ln = lines[i];
    const cls = classify(ln);
    if (!cls) continue;
    // Suppress same-line spam (e.g. one-line const next to a banner)
    if (cls.kind !== 'section' && i - lastHeadingLine < MIN_LINES_BETWEEN_HEADINGS) continue;
    sections.push({ line: i + 1, kind: cls.kind, title: cls.title });
    if (cls.kind === 'section') lastHeadingLine = i;
  }
  return { lineCount: lines.length, sections };
}

function buildMarkdown() {
  const out = [];
  out.push('# Code map');
  out.push('');
  out.push('_Auto-generated by `node tools/codemap.mjs`. Do not edit by hand — run the tool again after major moves so a future contributor (human or LLM) lands on the right line with one `Read` call._');
  out.push('');
  for (const t of TARGETS) {
    const abs = path.join(ROOT, t.path);
    if (!fs.existsSync(abs)) continue;
    const { lineCount, sections } = scanFile(abs);
    out.push(`## \`${t.path}\` — ${t.label}`);
    out.push('');
    out.push(`Total lines: **${lineCount}**`);
    out.push('');
    if (!sections.length) { out.push('_(No banners detected.)_'); out.push(''); continue; }
    // Group by section heading; nest fn/const under the previous
    // section so readers can drill down.
    let lastSection = null;
    for (const s of sections) {
      if (s.kind === 'section') {
        if (lastSection) out.push('');
        out.push(`- **\`L${s.line}\`** — ${s.title}`);
        lastSection = s;
      } else if (s.kind === 'fn') {
        out.push(`  - \`L${s.line}\` fn \`${s.title}()\``);
      } else if (s.kind === 'const') {
        out.push(`  - \`L${s.line}\` const \`${s.title}\``);
      }
    }
    out.push('');
  }
  return out.join('\n');
}

function main() {
  const md = buildMarkdown();
  const target = path.join(ROOT, '.codemap.md');
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
    if (current.trim() !== md.trim()) {
      console.error('codemap stale — run `node tools/codemap.mjs` and commit the result.');
      process.exit(1);
    }
    console.log('codemap fresh.');
    return;
  }
  fs.writeFileSync(target, md);
  console.log('Wrote', path.relative(ROOT, target));
}

main();
